// config.js - Base de datos estática centralizada de LAPI

window.LAPI_CONFIG = {
    APP_VERSION: "v1.2.0 (Mayo 2026)",
    // ==========================================
    // 1. CATÁLOGO COMPARTIDO DE MÉDICOS
    // ==========================================
    medicos: [
        "Alanis Aparicio Ulises Jasiel",
        "Alberto Gomez",
        "Angeles Del Carmen Valenzuela Morales",
        "Angeles Velazquez Jennifer Tabata",
        "Angelica Itzel",
        "Angello",
        "Arizcorreta Colchado Ivonne Guadalupe",
        "Bustos Gonzalez Claudia Montserrat",
        "Cabrera Hernandez Ana Beatriz",
        "Cabrera Velazquez Miguel Ramon",
        "Camacho Ortiz Barbara Alejandra",
        "Cervantes Erendira Montserrat",
        "Chavez Muñoz Brizeth Alondra",
        "Contreras Herrera Maribel del Carmen",
        "Cruz Zavala Lucero",
        "Cuevas Garcia Javier Alejandro",
        "David Emmanuel",
        "Delgadillo Fredy Sebastian",
        "Delgado Elizalde Diana Edit",
        "Diego Arias",
        "Dominguez Mojica Jannet Alejandra",
        "Dulce Maria",
        "Duque Hernandez Jaqueline",
        "Elzy Chacon",
        "Escobar Rios Erika Yeraldi",
        "Estefany Becherel",
        "Fernanda",
        "Fernandez Contreras Karla Alitzel",
        "Flores Miranda Adriana",
        "Fuerte Morales Aleydis",
        "Garcia Malanco Jose Antonio",
        "Garcia Morado Ana Lourdes",
        "Giovanni Mariano",
        "Giselle Vizuet",
        "Gonzalez Lucas Alondra Estefania",
        "Hernandez Gonzalez Giovanni Mariano",
        "Ingrid Bernal",
        "Isabel Palma",
        "Islas Veivar Patricia Guadalupe",
        "Izaguirre Rojas Martha",
        "Jannet Alejandra",
        "Jazmin Morales",
        "Jose Alejandro",
        "Jose Juan",
        "Juan Manuel",
        "Leilany Montserrat Sanchez",
        "Lino Reynoso Deany Alondra",
        "Lopez Lopez Guadalupe Mireya",
        "Lucero Cruz",
        "Luevano Sanchez Sara Maria",
        "Macedo Licona Sandra Lilian",
        "Maria Guadalupe Zapata Hernandez",
        "Mariana Gaviño",
        "Mauricio Ruiz",
        "Medina Molina Guadalupe",
        "Monjaraz Sanchez Viviana",
        "Montoya Linares Rebeca",
        "Muñoz Perez Jazmin Nayeli",
        "Olvera Aguilar Diana Karen",
        "Ordoñez Mejia Luis Enrique",
        "Patricia Kassandra",
        "Paulina Alba",
        "Perez Bautista Esther",
        "Pineda Lopez Patricia",
        "Ramirez Ramirez Carlos Antonio",
        "Reyes Perez Victor",
        "Rodriguez Peña Dolores Berenice",
        "Rueda Pedraza Sabine Shecid",
        "Ruz Chumba Nazaret Jaqueline",
        "Saavedra Olvera Miriam Elizabeth",
        "Salinas Rojas Miguel Angel",
        "Sanchez Gonzalez Alma del Rosario",
        "Sanchez Sanchez Claudia Ivonne",
        "Soriano Arvea Ariagna Anahi",
        "Susana Cayetano",
        "Tahuilan Enciso Cinthia",
        "Toriz Segura Jessica Noemi",
        "Vazquez Euan Daniela de los Angeles",
        "Velasco Duran Araceli",
        "Yasmin Cruz",
        "Yirelka Yeraldine",
        "Zarate Flores Myriam Alejandra"
    ].sort(),

    // ==========================================
    // 2. CATÁLOGO DE SUCURSALES OFICIALES
    // ==========================================
    sucursales: [
        "Balbuena", 
        "Calzada del Hueso", 
        "Condesa", 
        "Cuautitlán", 
        "Encuentro Fortuna", 
        "Gabriel Mancera", 
        "Gran Sur", 
        "Interlomas", 
        "Lindavista", 
        "Lomas Verdes", 
        "Martín Carrera", 
        "Mérida, Centro", 
        "Metepec", 
        "Mixcoac", 
        "Plateros", 
        "Plaza Central", 
        "Polanco", 
        "Revolución", 
        "Santa Fe", 
        "Santa Martha", 
        "Satélite"
    ].sort(),

    // ==========================================
    // 3. CATÁLOGO COMPARTIDO DE EMPRESAS
    // ==========================================
    empresas: [
        "3B (TIENDAS TRES B)",
        "ABBOTT LABORATORIES",
        "ACEITES SUPERFINOS",
        "ACEROS LEVINSON",
        "ACTIA DE MEXICO",
        "ADMINISTRACION DE RIESGOS BAL",
        "AEROMEXICO",
        "AFIRME SEGUROS",
        "ALMEXA",
        "ALSTOM FERROVIARIA",
        "ALSTOM FERROVIARIA CIUDAD AZTECA",
        "ALSTOM FERROVIARIA ROSARIO",
        "ALSTOM FERROVIARIA TICOMAN",
        "ALSTOM FERROVIARIA TREN MAYA",
        "ANTIBIOTICOS DE MEXICO",
        "AON RISK SOLUTIONS",
        "ARCELORMITTAL",
        "ARCOSA INDUSTRIES",
        "ASA CDMX",
        "ASOCIACION NACIONAL DE ACTORES",
        "ASSOCIATED SPRING",
        "ATLAS COPCO",
        "ATLAS GUADALAJARA",
        "AVANTOR",
        "AVIENT COLORANTS",
        "AXA SEGUROS",
        "AZ FINE CHEMICAL",
        "BANAMEX",
        "BANCO DE MEXICO",
        "BANCOMEXT",
        "BANJERCITO",
        "BARCEL TOLUCA",
        "BASF COATINGS MEXICANA",
        "BAXTER HEALTHCARE",
        "BBVA MEXICO",
        "BECTON DICKINSON",
        "BERRY BPREX PLASTIC - AMCOR",
        "BIMBO",
        "BIMBO AZCAPOTZALCO",
        "BIMBO SANTA MARIA",
        "BIODIST",
        "BIOPAPEL",
        "BOEHRINGER INGELHEIM PROMECO",
        "BONAFONT",
        "BP ESTACIONES Y SERVICIOS",
        "BUREAU VERITAS",
        "BYVA MINERALES",
        "C&W OPERACION DE SERVICIOS",
        "CARVAJAL TECNOLOGIA Y SERVICIOS",
        "CASA LUMBRE",
        "CASA LUMBRE AXOCOPAN",
        "CASA LUMBRE PUEBLA",
        "CEMEX ATOTONILCO",
        "CEMEX BARRIENTOS",
        "CEMEX MERIDA",
        "CEMEX SAN ANTONIO",
        "CEMEX SANTA CATARINA",
        "CEMEX TLAHUAC",
        "CENTRO DE DISTRIBUCION OXXO",
        "CFE",
        "CLOROX DE MEXICO",
        "COCA COLA",
        "COCA COLA EXPORT",
        "COCA COLA FEMSA",
        "COCA COLA LOS REYES",
        "COCA COLA OJUELOS",
        "COCA COLA TERRACOTA",
        "COCA COLA TOLUCA",
        "COMPAÑIA EDITORIAL",
        "COMPAÑIA NOC",
        "COMSA INFRAESTRUCTURAS",
        "CONCRETOS FORTALEZA (TPM)",
        "CONDUMEX",
        "CONSULMED",
        "CONSULMED ELEVADORES SCHINDLER",
        "CONSULMED MSD",
        "CONSULMED SIEMENS",
        "CONSULTORES MEDICOS",
        "CORPORATIVO DL DENTILAB",
        "CORTEVA AGRISCIENCE",
        "CRYINFRA",
        "DESARROLLO LOGISTICO",
        "DESTILERÍA Y BODEGA ABASOLO",
        "DICIPA",
        "DISTRIBUIDORA DE LACTEOS ALGIL",
        "DLP MEDICAL",
        "DUN & BRADSTREET",
        "DURANDCO CORPORATE SERVICES",
        "E KABEL MEXICO",
        "ECOLAB",
        "ELEMENTIA",
        "EMPRESA MEXICANA DE MANUFACTURAS",
        "ENGIE MEXICO",
        "ENTSERV ENTERPRISE SERVICES",
        "EULEN MEXICO",
        "EXPLOITANT HOTELIER -HYATT",
        "FABRICA DE HARINAS ELIZONDO",
        "FACTOR X",
        "FARMACEUTICA RAYERE",
        "FCC CONSTRUCCION",
        "FIRST CALL SEGURIDAD PRIVADA",
        "FONATUR",
        "FRUTAS CONCENTRADAS",
        "GALDERMA DE MEXICO",
        "GERDAU CORSA",
        "GIVAUDAN DE MEXICO",
        "GRUPO COBRA",
        "GRUPO EIRA",
        "GRUPO IND POSEIDON",
        "GRUPO MEXICO INFRAESTRUCTURA",
        "GRUPO ONEST LOGISTICS",
        "GRUPO POLAK",
        "GRUPO PRODENSA",
        "GRUPO TAIFELDS",
        "HEWLETT-PACKARD",
        "HIR SEGUROS",
        "HOLCIM ATLACOMULCO",
        "HOLCIM CUAUTLA",
        "HOLCIM CUERNAVACA",
        "HOLCIM POLOTITLAN",
        "HUMANTOP",
        "HUSSMANN INDUSTRIAS FRIGORIFICAS",
        "IBERCHEM",
        "ICEE DE MEXICO",
        "IGS ASISTENCIA",
        "IKE ASISTENCIA",
        "IMPULSORA DE MERCADOS DE MEXICO",
        "INDUSTRIAS METALICAS",
        "INDUSTRIAL ACEITERA",
        "INGETEAM POWER TECHNOLOGY",
        "INGREDION",
        "JAFRA COSMETICS",
        "JLL MEXICO",
        "JOHNSON & JOHNSON",
        "JUGOS DEL VALLE",
        "JUGOS DEL VALLE LA TORRE",
        "JUGOS DEL VALLE LERMA",
        "JUGOS DEL VALLE TEPOTZOTLAN",
        "KAESER COMPRESORES",
        "KEUBIO",
        "KONE MEXICO",
        "LA CAZADORA",
        "LA LATINOAMERICANA SEGUROS",
        "LABORATORIOS LIOMONT",
        "LAPI",
        "LITOGRÁFICA INGRAMEX",
        "LIVERPOOL",
        "LIVERPOOL CD JARDIN",
        "LIVERPOOL CENTRO",
        "LIVERPOOL INTERLOMAS",
        "LIVERPOOL LAS ANTENAS",
        "LIVERPOOL MITIKAH",
        "LIVERPOOL PERISUR",
        "LIVERPOOL PLAN",
        "LIVERPOOL SANTA FE",
        "LIVERPOOL TEZONTLE",
        "LOREAL",
        "M3 CODICE INTEGRAL",
        "MAGNA ASSEMBLY SYSTEMS",
        "MANPOWER",
        "MANUCHAR INTERNACIONAL",
        "MATERIAS PRIMAS",
        "MCCORMICK DE MEXICO",
        "MCCORD PAYEN",
        "MECANICA TEK",
        "MEDIACCESS",
        "MERCK",
        "MES TECNOLOGIA EN SERVICIOS",
        "MOTA ENGIL MEXICO",
        "NAFINSA",
        "NEWREST CATERING",
        "NOVARTIS",
        "NYSCO",
        "OMEGA MEXICO",
        "ORGANON PHARMA",
        "OWENS CORNING",
        "OXXO AZCAPOTZALCO",
        "OXXO SMO",
        "PARKER HANNIFIN",
        "PLAN SEGURO",
        "POLIRESINAS",
        "PORCELANITE LAMOSA",
        "PREVEM SEGUROS",
        "PROBIOMED",
        "PROCTER & GAMBLE",
        "PRODUCTOS INNOVADOR",
        "PRODUCTOS RICH",
        "PROFILATEX",
        "PROMECO",
        "PROVEEDORA MEXICANA DE MONOFILAMENTOS",
        "PROXIMIDAD Y LOGISTICA CHALCO",
        "PROXIMIDAD Y LOGISTICA MORELOS",
        "PROXIMIDAD Y LOGISTICA PACHUCA",
        "QUALITAS COMPAÑIA DE SEGUROS",
        "QUANTUM ENERGIA",
        "RED RING",
        "RHI MAGNESITA",
        "ROTOPLAS",
        "RYDER CAPITAL",
        "SABORMEX GUADALAJARA",
        "SAFMEX TOLUCA",
        "SC JOHNSON AND SON",
        "SCHNEIDER ELECTRIC",
        "SEGURO AXA",
        "SEGURO INBURSA",
        "SEGURO ZURICH",
        "SEGUROS ARGOS",
        "SEGUROS ATLAS",
        "SERVICIOS ELECTRONICOS GLOBALES",
        "SIFATEC TULA 1",
        "SIFATEC TULA 2",
        "SIGMA ALIMENTOS",
        "SNF FLOERGER",
        "SOCIEDAD HIPOTECARIA FEDERAL",
        "SODEXO",
        "SODEXO CECAT SUR",
        "SOLENIS TECHNOLOGIES",
        "SUDARSHAN",
        "TACA DE MEXICO",
        "TISK SOLUCIONES",
        "TOYOTA TSUSHO",
        "TRANSFORMADORA INDUSTRIAL",
        "TRINITY RAIL",
        "UNIVAR SOLUTIONS",
        "UPS MEXICO",
        "USK INTENACIONAL",
        "USME",
        "VALEANT",
        "VOLVO GROUP",
        "WSP MEXICO",
        "ZETA ADMINYTO"
    ].sort(),
  
    // ==========================================
    // 4. TIPOS DE ESTUDIOS EXCLUSIVOS (FORÁNEOS)
    // ==========================================
    estudiosForaneos: [
        "Espirometría", "Audiometría", "Historia Clínica", 
        "Examen de Capacidad Visual", "Nórdico", "Seguro"
    ].sort(),

    // ==========================================
    // 5. TIPOS DE ESTUDIOS EXCLUSIVOS (SUCURSALES)
    // ==========================================
    estudiosSucursales: [
        "Historia Clínica Empresa", "Historia Clínica LAPIWEB", "Consulta Médica", 
        "Seguro", "Audiometría", "Espirometría", "Electrocardiograma", 
        "Agudeza Visual", "Logoaudiometría", "Timpanometría", "Certificado", 
        "Nórdico", "Otro"
    ],

    // ==========================================
    // 6. MAPEO DE EXCELS (SUCURSALES)
    // ==========================================
    mapeoExcelsSucursales: { 
        "HC": "HC", 
        "EXAMEN MEDICO": "HC", 
        "SEGURO": "Seguro", 
        "AUDIOMETRIA": "Audiometría", 
        "ESPIROMETRIA": "Espirometría", 
        "ELECTROCARDIOGRAMA": "Electrocardiograma", 
        "AGUDEZA VISUAL": "Agudeza Visual", 
        "LOGOAUDIOMETRIA": "Logoaudiometría", 
        "TIMPANOMETRIA": "Timpanometría", 
        "CERTIFICADO": "Certificado", 
        "NORDICO": "Nórdico", 
        "OTRO": "Otro" 
    }, // <-- Asegúrate de que esta coma esté aquí para separar

    // ==========================================
    // 7. DICCIONARIO CONTEXTUAL (SUCURSAL -> INICIALES)
    // ==========================================
    diccionarioIniciales: {
        "BALBUENA": {
            "JM": "Muñoz Perez Jazmin Nayeli",
            "MZ": "Zarate Flores Myriam Alejandra",
            "EP": "Perez Bautista Esther"
        },
        "CUAUTITLAN": {
            "JA": "Angeles Velazquez Jennifer Tabata",
            "CBG": "Bustos Gonzalez Claudia Montserrat",
            "MCG": "Cervantes Erendira Montserrat",
            "AV": "Velasco Duran Araceli",
            "MSH": "Leilany Montserrat Sanchez"
        },
        "CONDESA": {
            "UA": "Alanis Aparicio Ulises Jasiel",
            "MC": "Contreras Herrera Maribel del Carmen"
        },
        "CALZADA DEL HUESO": {
            "AF": "Flores Miranda Adriana",
            "PI": "Islas Veivar Patricia Guadalupe",
            "CR": "Ramirez Ramirez Carlos Antonio",
            "BC": "Camacho Ortiz Barbara Alejandra"
        },
        "ENCUENTRO FORTUNA": {
            "AD": "Dominguez Mojica Jannet Alejandra",
            "JC": "Cuevas Garcia Javier Alejandro",
            "AF": "Fuerte Morales Aleydis"
        },
        "GABRIEL MANCERA": {
            "VM": "Monjaraz Sanchez Viviana",
            "LO": "Ordoñez Mejia Luis Enrique"
        },
        "INTERLOMAS": {
            "EE": "Escobar Rios Erika Yeraldi",
            "CT": "Tahuilan Enciso Cinthia"
        },
        "LINDAVISTA": {
            "SD": "Delgadillo Fredy Sebastian",
            "AG": "Gonzalez Lucas Alondra Estefania",
            "DL": "Lino Reynoso Deany Alondra"
        },
        "LOMAS VERDES": {
            "MIR": "Martha Izaguirre Rojas",
            "BD": "Dulce Maria Buenrostro Perez",
            "LC": "Cruz Zavala Lucero",
            "JT": "Toriz Segura Jessica Noemi"
        },
        "MARTIN CARRERA": {
            "LS": "Luevano Sanchez Sara Maria",
            "LUEVANO": "Luevano Sanchez Sara Maria"
        },
        "METEPEC": {
            "RML": "Montoya Linares Rebeca",
            "SSR": "Rueda Pedraza Sabine Shecid",
            "MRC": "Cabrera Velazquez Miguel Ramon"
        },
        "MIXCOAC": {
            "PP": "Paula Pichardo",
            "BF": "Brenda Flores"
        },
        "PLATEROS": {
            "PA": "Paulina Alba",
            "AM": "Garcia Morado Ana Lourdes"
        },
        "PLAZA CENTRAL": {
            "IA": "Arizcorreta Colchado Ivonne Guadalupe",
            "BC": "Chavez Muñoz Brizeth Alondra"
        },
        "POLANCO": {
            "KF": "Fernandez Contreras Karla Alitzel",
            "AS": "Soriano Arvea Ariagna Anahi",
            "GH": "Hernandez Gonzalez Giovanni Mariano",
            "PP": "Pineda Lopez Patricia"
        },
        "SANTA FE": {
            "GM": "Medina Molina Guadalupe"
        },
        "SANTA MARTHA": {
            "JD": "Duque Hernandez Jaqueline",
            "AD": "Dominguez Mojica Jannet Alejandra",
            "AC": "Cabrera Hernandez Ana Beatriz",
            "LC": "Lucero Cruz"
        },
        "SATELITE": {
            "MASR": "Salinas Rojas Miguel Angel",
            "MGZH": "Maria Guadalupe Zapata Hernandez",
            "LLGM": "Lopez Lopez Guadalupe Mireya"
        },
        "REVOLUCION": {
            "MS": "Saavedra Olvera Miriam Elizabeth",
            "VR": "Reyes Perez Victor",
            "CS": "Sanchez Sanchez Claudia Ivonne",
            "DO": "Olvera Aguilar Diana Karen"
        }
    }
};
